name: Docker Image CI

on:
  push:
    tags:
      - 'v*'  # O workflow será acionado apenas para tags que começam com 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necessário para obter todas as tags e histórico

      - name: Verify tag is from main branch
        run: |
          git fetch origin main
          if [ "$(git rev-list -n 1 origin/main)" != "$(git rev-list -n 1 $GITHUB_SHA)" ]; then
            echo "Tag was not created from the main branch. Exiting."
            exit 1
          fi

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ordini_client:latest .

      - name: Push the Docker image
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/ordini_client:latest ${{ secrets.DOCKERHUB_USERNAME }}/ordini_client:${{ github.ref_name }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ordini_client:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ordini_client:${{ github.ref_name }}

      - name: Trigger Deploy on Render
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST -d '' "$RENDER_DEPLOY_HOOK_URL"
